import { handleRegister, render } from './register.js';
import { handleLogin, } from './login.js';
import { getLoginPage, getRegisterPage, getProfilePage, getEditPage, closeAddJobPostPopup, getForgotPwForm, closeForgotPwForm } from './getPage.js';
import { handleFeed } from './feed.js';
import { handleProfile } from './profile.js';
import { makeEditProfile } from './editProfile.js';
import { closeAddEmailPopup } from './getPage.js';
import { resetFile } from './editProfile.js';
import { renderForgotPw, renderNewPw } from './forgotPw.js';
import { searchJob, checkIfString } from './searchPosts.js';

window.handleRegister = handleRegister;
window.handleLogin = handleLogin;
window.handleFeed = handleFeed;
window.handleProfile = handleProfile;
window.makeEditProfile = makeEditProfile;
window.render = render;
window.getLoginPage = getLoginPage;
window.getRegisterPage = getRegisterPage;
window.getProfilePage = getProfilePage;
window.getEditPage = getEditPage;
window.closeAddEmailPopup = closeAddEmailPopup;
window.closeAddJobPostPopup = closeAddJobPostPopup;
window.resetFile = resetFile;
window.getForgotPwForm = getForgotPwForm;
window.renderForgotPw = renderForgotPw;
window.closeForgotPwForm = closeForgotPwForm;
window.renderNewPw = renderNewPw;
window.searchJob = searchJob;
window.checkIfString = checkIfString;
